version: '3'
services:
  redis:
    image: redis
    container_name: discushub_redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/usr/share/redis/data
 
volumes:
  redis_data:
    driver: local